/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author misbah alkhafadh
 */
public class CobaLagi extends javax.swing.JFrame {

    /**
     * Creates new form CobaLagi
     */
    public CobaLagi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskCoba = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Prima = new javax.swing.JMenu();
        fibonasi = new javax.swing.JRadioButtonMenuItem();
        prima = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DeskCobaLayout = new javax.swing.GroupLayout(DeskCoba);
        DeskCoba.setLayout(DeskCobaLayout);
        DeskCobaLayout.setHorizontalGroup(
            DeskCobaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        DeskCobaLayout.setVerticalGroup(
            DeskCobaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        Prima.setText("File");

        fibonasi.setSelected(true);
        fibonasi.setText("Deret Fibonasi");
        fibonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fibonasiActionPerformed(evt);
            }
        });
        Prima.add(fibonasi);

        prima.setSelected(true);
        prima.setText("Bilangan Prima");
        prima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primaActionPerformed(evt);
            }
        });
        Prima.add(prima);

        jMenuBar1.add(Prima);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskCoba)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskCoba)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fibonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fibonasiActionPerformed
        Buka bukaAja = new Buka();
        bukaAja.show();
        DeskCoba.add(bukaAja);
    }//GEN-LAST:event_fibonasiActionPerformed

    private void primaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primaActionPerformed
        DeskPrima bukaAja = new DeskPrima();
        bukaAja.show();
        DeskCoba.add(bukaAja);
    }//GEN-LAST:event_primaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobaLagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobaLagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobaLagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobaLagi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CobaLagi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskCoba;
    private javax.swing.JMenu Prima;
    private javax.swing.JRadioButtonMenuItem fibonasi;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem prima;
    // End of variables declaration//GEN-END:variables
}
